# -*- coding: utf-8 -*-
"""model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T0_GdzlT1NKuNhMatnafjSMTtx6tEa4e

## model
"""

!mkdir -p data
!wget https://raw.githubusercontent.com/SophonPlus/ChineseNlpCorpus/master/datasets/waimai_10k/waimai_10k.csv -O data/waimai_10k.csv
!pip install jieba
!pip install torch

# 1. 導入所需套件

import os
import math
import random

# 第3方套件
import jieba
import numpy as np
import pandas as pd
import torch
from torch.utils.data import DataLoader
from torch.nn.utils.rnn import pad_sequence
from torch.nn import TransformerEncoder, TransformerEncoderLayer
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

df = pd.read_csv("./data/waimai_10k.csv")

train_data, test_data = train_test_split(
    df,
    test_size=0.2
)
train_data, validation_data = train_test_split(
    train_data,
    test_size=0.1
)

"""### 設定訓練流程"""

!pip install simpletransformers

# 載入所需的資料格式

train_bert = pd.DataFrame({
    "text": train_data["review"],
    "label": train_data["label"]
})
valid_bert = pd.DataFrame({
    "text": validation_data["review"],
    "label": validation_data["label"]
})
test_bert = list(test_data["review"])

from simpletransformers.classification import ClassificationModel, ClassificationArgs


model_args = ClassificationArgs(sliding_window=True)

model = ClassificationModel(
    "bert",
    "bert-base-chinese",
    args=model_args,
)

model.train_model(
    train_df=train_bert,
    eval_df=valid_bert
)

from google.colab import drive
drive.mount('/content/drive')

import pickle
with open('/content/drive/MyDrive/AI final/model.pickle', 'rb') as f:
    modell = pickle.load(f)

print(model.predict(["不用"])[0])
print()

